//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFLogMessage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int AnimalId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
    }
}
